name: CICD

on:
  push:
    branches:   # ✅ correct spelling
      - main    # ✅ push to main branch triggers workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3  # ✅ not 'users', correct 'uses'
      
      - name: Login to Docker Hub
        run: echo "Pagani@2000" | docker login -u "mdnihal" --password-stdin

      - name: Build Docker Image
        run: docker build -t mdnihal/reactjs-app .

      - name: Publish Image to Docker Hub
        run: docker push mdnihal/reactjs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted   # your self-hosted runner name

    steps:
      - name: Pull image from Docker Hub
        run: docker pull mdnihal/reactjs-app:latest

      - name: Delete Old Container
        run: docker rm -f reactcontainer || true

      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name reactcontainer mdnihal/reactjs-app:latest









